# Generated by Django 4.1.1 on 2022-11-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
