# Generated by Django 4.1.1 on 2022-11-20 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('author', '0002_alter_author_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id']},
        ),
    ]
