# Generated by Django 4.1.1 on 2022-12-12 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/%m/%Y')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA')),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[(0, 'Not specified'), (1, 'Male'), (2, 'Female')], default=0,
                                         max_length=15)),
                ('verified', models.BooleanField(default=False)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
