# Generated by Django 4.1.1 on 2022-12-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0002_remove_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('N', 'Not specified'), ('M', 'Male'), ('F', 'Female')], default='N',
                                   max_length=15),
        ),
    ]
