# Generated by Django 4.1.1 on 2022-12-12 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0003_alter_profile_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sex',
            new_name='gender',
        ),
    ]
