# Generated by Django 4.1.1 on 2022-12-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0004_rename_sex_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%m/%Y'),
        ),
    ]
