# Generated by Django 4.1.4 on 2022-12-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0006_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%m/%Y'),
        ),
    ]
