# Generated by Django 4.1.4 on 2022-12-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='avatars/%m/%Y'),
        ),
    ]
