# Generated by Django 4.1.1 on 2022-11-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0007_alter_order_end_at_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plated_end_at',
            field=models.DateTimeField(null=True),
        ),
    ]
