# Generated by Django 4.1.1 on 2022-11-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0008_alter_order_plated_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='plated_end_at',
            field=models.DateTimeField(),
        ),
    ]
